### ISSUE TITLE
pcapfix states that a valid pcap file built by current tcpdump or tshark is corrupt

### ISSUE THREAD

**Issue by fxlb** [Rup0rt/pcapfix#12]
Hi,
Currently, the default capture length for pcap files by tcpdump (and tshark) is `262144`.
For such valid pcap files, pcapfix gives the message:
[-] The global pcap header seems to be corrupt! ==> CORRECTED
and correct the capture length to `65535`.
Could you change this behaviour ?

**Comment by Rup0rt** [comment]
Thanks for reporting this bug. I didn't recognize the snaplen change in the past and gonna fix this soon!

**Comment by fxlb** [comment]
Thanks!
