### ISSUE TITLE
Infinite loop ?

### ISSUE THREAD

**Issue by fxlb** [Rup0rt/pcapfix#13]
Hi,
It seems that pcapfix has an infinite loop with this pcap file:
[mobility_opt_asan.pcap.gz](https://github.com/Rup0rt/pcapfix/files/2197601/mobility_opt_asan.pcap.gz)
with -d option

**Comment by Rup0rt** [comment]
Fixed, but I still have a problem with this file. The global pcap header snap length is 70 bytes, but the captured packets are 100 bytes in size. At this moment the packets are handled as broken. Is this a wanted behavior? From my point of view there are two possibilities:

1) global pcap header snap length is ignored
2) global pcap header snap length is adjusted based on the largest packet in file (false positives may occur)

What do you think?

**Comment by Rup0rt** [comment]
Yes, I tested it as well. Tcpdump/Tshark do (also) not care about global pcap header snap length. So this might be a reason for ignoring it as well. I use this field in pcapfix for plausibility checks when scanning for valid packets but I can use the maximum snap length as an less accurate alternative.

**Comment by Rup0rt** [comment]
I added a soft mode (-s) to pcapfix that disables some checks that do not break the file if they occur. This way even the packets that would be broken under hard circumstances can be identified.
