### ISSUE TITLE
Packet detection inside another packet leads to corruption.

### ISSUE THREAD

**Issue by mdeweerd** [Rup0rt/pcapfix#21]
The example is for a good pcap file - I tried to fix another pcap file that is only partially corrupted, but applying pcapfix did more harm than good for the reason put forward in this test case.

The corrected file has less packets than good source pcap.

The testcase has a 'tc.sh' file that acts on the sample file and demnstrates that the output has less packets than the original while the original is perfectly fine.
[pcapfixtc20201227.zip](https://github.com/Rup0rt/pcapfix/files/5745043/pcapfixtc20201227.zip)

**Comment by Rup0rt** [comment]
Seems that pcap packet header size can be smaller than fixed limit of 10 bytes. I added an exception for DLT 195 which should fix your problem. Thank you very much for your file, I am going to use it in future test cases.
