### ISSUE TITLE
add fix for interface type error

### ISSUE THREAD

**Issue by sergey-safarov** [Rup0rt/pcapfix#23]
I cannot parse `pcap` in the attached file.
Example:
```
[safarov@safarov-dell tmp]$ tcpdump -r interface-type-error.pcapng
reading from file /home/safarov/interface-type-error.pcapng, link-type LINUX_SLL (Linux cooked v1)
tcpdump: pcap_loop: an interface has a type 1 different from the type of the first interface
```
Could you also add support to fix this type of error?

[interface-type-error.pcapng.gz](https://github.com/Rup0rt/pcapfix/files/6397233/interface-type-error.pcapng.gz)

**Comment by Rup0rt** [comment]
Hi sergey,

I checked your file and pcapng specifications and it does look to me that having 2 interfaces with different types is good for the pcapng file format. So it seems that this is a missing feature in tcpdump.

Let me know, if you think that I am wrong.

**Comment by sergey-safarov** [comment]
Yes, you a right.
I have downloaded [`many_interfaces.pcapng`](https://wiki.wireshark.org/Development/PcapNg?action=AttachFile&do=get&target=many_interfaces.pcapng) from [page](https://wiki.wireshark.org/Development/PcapNg?action=AttachFile&do=view&target=many_interfaces.pcapng)
[Relevant page](https://wiki.wireshark.org/Development/PcapNg).

And then checked using the same command and get the same error.
```
[user@example home]$ tcpdump -r ~/Downloads/many_interfaces.pcapng 
reading from file /home/safarov/Downloads/many_interfaces.pcapng, link-type EN10MB (Ethernet)
tcpdump: pcap_loop: an interface has a type 0 different from the type of the first interface
```

So looks like the required support of PCAPNG support in the other program or [convert to PCAP format](https://www.netresec.com/?page=Blog&month=2012-12&post=HowTo-handle-PcapNG-files).

[libpcap do not support `pcapng` format](https://github.com/the-tcpdump-group/libpcap/issues/728)
