### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by JamieSlome** [Rup0rt/pcapfix#24]
Hello,

We recently received a vulnerability disclosure from @geeknik against your repository. I couldn't find a security policy against your repository and wasn't sure if the e-mail in your `README.md` was appropriate for this.

Do you have a preferred place you would like me to send the details to? Otherwise, you can view the advisory [here](https://huntr.dev/bounties/1-Rup0rt/pcapfix/).

It is private to yourself and the discloser of the report.

If you have any questions, my door is open!

-- Jamie from huntr.dev

**Comment by Rup0rt** [comment]
I cannot reproduce this crash atm. Need further information to provide a fix.

**Comment by Rup0rt** [comment]
Fixed by commit fb723c8374db2f0e8b394570e433e4cc70f07b75
