### ISSUE TITLE
Can I use this tool to fix the packet data corrupted? if not, is there any tool can do it?

### ISSUE THREAD

**Issue by chenchampion** [Rup0rt/pcapfix#30]
Can I use this tool to fix the packet data corrupted? if not, is there any tool can do it?

**Comment by smith558** [comment]
Yes

**Comment by Rup0rt** [comment]
No, pcapfix only fixes pcap format. It does not repair any corrupted data. There might be a way to brute force some data based on packet checksum but I do not know any tool that can handle this.
