### ISSUE TITLE
Link in pcap_kuznet.h is dead

### ISSUE THREAD

**Issue by marek22k** [Rup0rt/pcapfix#34]
The link http://tcpreplay.synfin.net/doxygen_yhsiam/tcpcapinfo_8c-source.html refers to a 404 page. Perhaps it could be updated? Alternatively, the source file could be referenced directly: https://github.com/appneta/tcpreplay/blob/master/src/tcpcapinfo.c

https://github.com/Rup0rt/pcapfix/blob/master/pcap_kuznet.h#L29

**Comment by Rup0rt** [comment]
Thanks! I will put this into next release.
